// scripts/gen-config.mjs: .env → js/firebase-config.js. Node-only (temp files,
// git); tests.html skips this file. Uses made-up values only, never the real key.

import { test, skip, assert, assertEqual, assertDeepEqual } from './runner.js';
import { readFileSync, writeFileSync, mkdtempSync, existsSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, dirname } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { execFileSync } from 'node:child_process';
import { parseEnv, readEnv, configFromEnv, generateConfig, missingKeys, ENV_KEYS } from '../scripts/gen-config.mjs';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const tmp = mkdtempSync(join(tmpdir(), 'pipeline-config-'));
let n = 0;
const envFile = text => {
  const file = join(tmp, `t${++n}.env`);
  writeFileSync(file, text);
  return file;
};
const NO_ENV = {}; // no real environment variables leak into these tests

const FULL = `FIREBASE_API_KEY=test-key-123
FIREBASE_AUTH_DOMAIN=demo-app.firebaseapp.com
FIREBASE_PROJECT_ID=demo-app
FIREBASE_STORAGE_BUCKET=demo-app.firebasestorage.app
FIREBASE_MESSAGING_SENDER_ID=111222333
FIREBASE_APP_ID=1:111222333:web:abc
`;

/** Import a generated module fresh (a unique URL defeats the module cache). */
async function load(file) {
  return (await import(`${pathToFileURL(file).href}?v=${Date.now()}${Math.random()}`)).FIREBASE_CONFIG;
}

test('parseEnv: comments, blank lines, export, quotes and trailing comments', () => {
  assertDeepEqual(parseEnv(`# comment
export FIREBASE_API_KEY = "quoted value" # trailing
FIREBASE_AUTH_DOMAIN='single quoted'

FIREBASE_PROJECT_ID=plain # note
FIREBASE_APP_ID="has # inside"
not a line
FIREBASE_STORAGE_BUCKET=
`), {
    FIREBASE_API_KEY: 'quoted value',
    FIREBASE_AUTH_DOMAIN: 'single quoted',
    FIREBASE_PROJECT_ID: 'plain',
    FIREBASE_APP_ID: 'has # inside',
    FIREBASE_STORAGE_BUCKET: ''
  });
  assertDeepEqual(parseEnv('A=1\r\nB=2\r\n'), { A: '1', B: '2' }, 'Windows line endings');
});

test('a full .env gives the complete firebaseConfig', () => {
  const config = configFromEnv(readEnv({ envFile: envFile(FULL), env: NO_ENV }));
  assertDeepEqual(config, {
    apiKey: 'test-key-123',
    authDomain: 'demo-app.firebaseapp.com',
    projectId: 'demo-app',
    storageBucket: 'demo-app.firebasestorage.app',
    messagingSenderId: '111222333',
    appId: '1:111222333:web:abc'
  });
  assertEqual(Object.keys(ENV_KEYS).length, 6);
});

test('a missing or blank .env gives an empty config (local mode)', () => {
  assertDeepEqual(configFromEnv(readEnv({ envFile: join(tmp, 'does-not-exist.env'), env: NO_ENV })), {});
  const blank = readEnv({ envFile: join(root, '.env.example'), env: NO_ENV });
  assertDeepEqual(configFromEnv(blank), {});
  assertDeepEqual(missingKeys(blank), ['FIREBASE_API_KEY', 'FIREBASE_PROJECT_ID', 'FIREBASE_APP_ID']);
  // One required key blank is still local mode, not a half-configured app.
  assertDeepEqual(configFromEnv(readEnv({ envFile: envFile(FULL.replace('FIREBASE_APP_ID=1:111222333:web:abc', 'FIREBASE_APP_ID=')), env: NO_ENV })), {});
});

test('real environment variables override .env; blank ones do not', () => {
  const values = readEnv({
    envFile: envFile(FULL),
    env: { FIREBASE_API_KEY: 'from-ci', FIREBASE_PROJECT_ID: '   ', UNRELATED: 'x' }
  });
  assertEqual(values.FIREBASE_API_KEY, 'from-ci');
  assertEqual(values.FIREBASE_PROJECT_ID, 'demo-app', 'a blank variable does not wipe the file value');
  const onlyEnv = readEnv({ envFile: join(tmp, 'none.env'), env: { FIREBASE_API_KEY: 'k', FIREBASE_PROJECT_ID: 'p', FIREBASE_APP_ID: 'a' } });
  assertDeepEqual(configFromEnv(onlyEnv), { apiKey: 'k', projectId: 'p', appId: 'a' });
});

// generateConfig writes a real module; import it to prove it is valid JS.
const generated = (async () => {
  const out = join(tmp, 'firebase-config.js');
  const full = generateConfig({ envFile: envFile(FULL), env: NO_ENV, out });
  const loadedFull = await load(out);
  const empty = generateConfig({ envFile: join(tmp, 'missing.env'), env: NO_ENV, out });
  const loadedEmpty = await load(out);
  return { full, loadedFull, empty, loadedEmpty, text: readFileSync(out, 'utf8') };
})();

export const configTestsDone = generated.then(({ full, loadedFull, empty, loadedEmpty, text }) => {
  test('generateConfig writes an importable js/firebase-config.js, full or empty', () => {
    assertEqual(loadedFull.projectId, 'demo-app');
    assertDeepEqual(loadedFull, full);
    assertDeepEqual(loadedEmpty, {});
    assertDeepEqual(empty, {});
    assert(text.includes('GENERATED by scripts/gen-config.mjs'), 'marked as generated');
  });
});

// Git checks need a checkout (a downloaded zip has no .git): skip, don't fail.
const gitTest = existsSync(join(root, '.git')) ? test : name => skip(name, 'not a git checkout');

gitTest('.env and the generated config are git-ignored; .env.example is not', () => {
  const ignored = file => {
    try {
      execFileSync('git', ['check-ignore', '-q', file], { cwd: root, stdio: 'pipe' });
      return true;
    } catch {
      return false;
    }
  };
  assert(ignored('.env'), '.env must be ignored');
  assert(ignored('.env.local'), '.env.* must be ignored');
  assert(ignored('js/firebase-config.js'), 'the generated config must be ignored');
  assert(!ignored('.env.example'), '.env.example must be committed');
});

gitTest('no tracked file contains a Firebase / Google API key', () => {
  const files = String(execFileSync('git', ['ls-files', '-z'], { cwd: root })).split('\0').filter(Boolean);
  assert(files.length > 20, `only ${files.length} tracked files: the scan is broken`);
  // Built from parts so this file itself never contains the pattern.
  const marker = ['AI', 'za'].join('');
  const hits = [];
  for (const file of files) {
    const full = join(root, file);
    if (!existsSync(full)) continue;
    if (readFileSync(full).includes(marker)) hits.push(file);
  }
  assertDeepEqual(hits, [], `API key text found in tracked files: ${hits.join(', ')}`);
  assert(!files.includes('.env') && !files.includes('js/firebase-config.js'), '.env / generated config are tracked');
  assert(files.includes('.env.example'), '.env.example should be tracked');
});
