// Headless test entry point: `node tests/run-node.mjs`
// The browser entry point is tests/tests.html — both share tests/runner.js.

import './calendar.test.js';
import './storage.test.js';
import './reminders.test.js';
import './theme.test.js';
import './phone-location.test.js';
import './dashboard.test.js';
import './ui-pure.test.js';
import { importerTestsDone } from './importer.test.js';
import { fileStoreTestsDone } from './file-store.test.js';
import './importer.xlsx.test.js';
import { cloudTestsDone } from './cloud.test.js';
import { saveStatusTestsDone } from './save-status.test.js';
import { configTestsDone } from './config.test.js';
import './transcript.test.js';
import { recordsTestsDone } from './records.test.js';
import './history.test.js';
import { groqTestsDone } from './groq.test.js';
import { minutesTestsDone } from './minutes.test.js';
import { storeTestsDone } from './store.test.js';
import './registry.test.js';
import './deals.test.js';
import './exporter.test.js';
import './timeline.test.js';
import './timetrack.test.js';
import './pickers.test.js';
import './drag.test.js';
import { chatTestsDone } from './chat.test.js';
import { aiTestsDone } from './ai.test.js';
import { workerTestsDone } from './worker.test.js';
import './deploy.test.js';
import './build.test.js';
import { report } from './runner.js';

await importerTestsDone;
await fileStoreTestsDone;
await cloudTestsDone;
await saveStatusTestsDone;
await configTestsDone;
await recordsTestsDone;
await groqTestsDone;
await minutesTestsDone;
await storeTestsDone;
await aiTestsDone;
await chatTestsDone;
await workerTestsDone;
const { failed } = report();
process.exitCode = failed ? 1 : 0;
