// Writes js/firebase-config.js from .env (plus real environment variables,
// which win). `npm run config`; also run before start, build and test.
//
// The Firebase *web* config is not a secret (it ships in every page), but it
// stays out of git: .env lives on your PC, js/firebase-config.js is generated
// and git-ignored. No .env (or blank values) → an empty config → local mode.

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join, dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

/** .env key → firebaseConfig field, in the order the console shows them. */
export const ENV_KEYS = {
  FIREBASE_API_KEY: 'apiKey',
  FIREBASE_AUTH_DOMAIN: 'authDomain',
  FIREBASE_PROJECT_ID: 'projectId',
  FIREBASE_STORAGE_BUCKET: 'storageBucket',
  FIREBASE_MESSAGING_SENDER_ID: 'messagingSenderId',
  FIREBASE_APP_ID: 'appId'
};

/** .env key → APP_CONFIG field: public app settings, not secrets. */
export const APP_ENV_KEYS = {
  WORKER_URL: 'workerUrl',
  GOOGLE_OAUTH_CLIENT_ID: 'googleClientId'
};

/** Without these three the app cannot sign in, so it stays in local mode. */
export const REQUIRED_KEYS = ['FIREBASE_API_KEY', 'FIREBASE_PROJECT_ID', 'FIREBASE_APP_ID'];

/**
 * Minimal .env parser: KEY=value lines, optional `export `, # comments, blank
 * lines, "double" or 'single' quoted values, and ` # trailing comments` after
 * unquoted values.
 */
export function parseEnv(text) {
  const out = {};
  for (const raw of String(text).split(/\r?\n/)) {
    const line = raw.trim();
    if (!line || line.startsWith('#')) continue;
    const m = line.match(/^(?:export\s+)?([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)$/);
    if (!m) continue;
    let value = m[2];
    const quoted = value.match(/^(["'])(.*)\1\s*(?:#.*)?$/);
    if (quoted) value = quoted[2];
    else value = value.replace(/\s+#.*$/, '').trim();
    out[m[1]] = value;
  }
  return out;
}

/** .env values, overridden by non-empty environment variables of the same name. */
export function readEnv({ envFile = join(root, '.env'), env = process.env } = {}) {
  const fromFile = existsSync(envFile) ? parseEnv(readFileSync(envFile, 'utf8')) : {};
  const merged = {};
  for (const key of [...Object.keys(ENV_KEYS), ...Object.keys(APP_ENV_KEYS)]) {
    const override = env[key] !== undefined && String(env[key]).trim() !== '' ? String(env[key]).trim() : undefined;
    merged[key] = override !== undefined ? override : (fromFile[key] || '').trim();
  }
  return merged;
}

/** Which required keys are blank. */
export function missingKeys(values) {
  return REQUIRED_KEYS.filter(key => !values[key]);
}

/** The firebaseConfig object, or {} (local mode) if a required key is blank. */
export function configFromEnv(values) {
  if (missingKeys(values).length) return {};
  const config = {};
  for (const [key, field] of Object.entries(ENV_KEYS)) if (values[key]) config[field] = values[key];
  return config;
}

/** APP_CONFIG: the Worker URL (without a trailing slash) and the OAuth client id; blanks left out. */
export function appConfigFromEnv(values) {
  const app = {};
  for (const [key, field] of Object.entries(APP_ENV_KEYS)) {
    const value = (values[key] || '').trim();
    if (value) app[field] = key === 'WORKER_URL' ? value.replace(/\/+$/, '') : value;
  }
  return app;
}

export function renderConfig(config) {
  return `// GENERATED by scripts/gen-config.mjs from .env: do not edit, do not commit.
// Change .env (see .env.example and README → Firebase setup), then
// \`npm run config\` (start, build and test run it for you).
// Empty = local mode: reminders stay in this browser, no sign-in.
export const FIREBASE_CONFIG = ${JSON.stringify(config, null, 2)};
`;
}

export function renderAppConfig(app) {
  return `// GENERATED by scripts/gen-config.mjs from .env: do not edit, do not commit.
// Worker URL and Google OAuth client id: public values, blank ones left out.
// Settings → Business can override the Worker URL per account.
export const APP_CONFIG = ${JSON.stringify(app, null, 2)};
`;
}

// Leave a file alone when nothing changed (no needless rebuild churn).
function writeIfChanged(file, text) {
  if (!existsSync(file) || readFileSync(file, 'utf8') !== text) writeFileSync(file, text, 'utf8');
}

/**
 * Read .env + environment, write js/firebase-config.js and js/app-config.js
 * (next to `out`), return the Firebase config.
 */
export function generateConfig({ envFile, env, out = join(root, 'js', 'firebase-config.js'), appOut = join(dirname(out), 'app-config.js') } = {}) {
  const values = readEnv({ envFile, env });
  const config = configFromEnv(values);
  writeIfChanged(out, renderConfig(config));
  writeIfChanged(appOut, renderAppConfig(appConfigFromEnv(values)));
  return config;
}

if (resolve(process.argv[1] || '') === fileURLToPath(import.meta.url)) {
  const config = generateConfig();
  console.log(config.projectId
    ? `js/firebase-config.js written for Firebase project "${config.projectId}".`
    : 'js/firebase-config.js written empty (no .env values): the app runs in local mode.');
}
